# Generated by Django 3.1.7 on 2021-03-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diary',
            field=models.TextField(null=True),
        ),
    ]
