# Generated by Django 3.1.7 on 2021-03-25 20:10

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_joy', django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=1620, size=20)),
                ('question_fear', django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=1620, size=20)),
                ('question_sad', django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=1620, size=20)),
                ('question_anger', django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=1620, size=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='diary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='list',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default=['joy', 'joy'], max_length=330, size=30),
            preserve_default=False,
        ),
    ]
